language: android

android:
  components:
    - tools
    - platform-tools
    - build-tools
    - android-19

script: ant debug

after_success:
  - mv bin/IMGSHR-debug.apk imgshr-debug-${TRAVIS_COMMIT:0:7}.apk
  - curl -k -X POST -F "file=@imgshr-debug-${TRAVIS_COMMIT:0:7}.apk" -F "token=$RELEASE_TOKEN" -F "version=${TRAVIS_COMMIT:0:7}" https://imgshr.orgizm.net/releases
