language: android
jdk: oraclejdk8

android:
  components:
    - tools
    - platform-tools
    - build-tools-25.0.2
    - android-25
    - extra-android-m2repository

script:
  - ./gradlew assembleDebug 
  - ./gradlew lintDebug

after_success:
  - mv app/build/outputs/apk/app-debug.apk imgshr-debug-${TRAVIS_COMMIT:0:7}.apk
  - curl -k -X POST -F "file=@imgshr-debug-${TRAVIS_COMMIT:0:7}.apk" -F "token=$RELEASE_TOKEN" -F "version=${TRAVIS_COMMIT:0:7}" -F "branch=$TRAVIS_BRANCH" https://imgshr.space/releases
