language: android

android:
  components:
    - tools
    - platform-tools
    - build-tools
    - android-19

script: gradle build

after_success:
  - mv app/builds/outputs/apk/app-debug.apk imgshr-debug-${TRAVIS_COMMIT:0:7}.apk
  - curl -k -X POST -F "file=@imgshr-debug-${TRAVIS_COMMIT:0:7}.apk" -F "token=$RELEASE_TOKEN" -F "version=${TRAVIS_COMMIT:0:7}" -F "branch=$TRAVIS_BRANCH" https://imgshr.space/releases
